### ISSUE TITLE
create a build process video

### ISSUE THREAD

**Issue by tkonheiser** [amosproj/amos2023ss03-qachat#72]
## User story
1. As a project team
2. I need a build process video
3. So that external parties can understand how to use the project

## Acceptance criteria
* a project demonstration is created for the industry partner
* a narrated video containing the clone, build, test, deploy (optional) and run steps is created
* the video is uploaded to the Deliverables folder sprint-05/build-process-video.mkv 

## Notes
[Video Requirements](https://docs.google.com/document/d/1ELeRxm30hb7p6sNm3OtpFh6HGTuOhBOW_DTp98vCRQY/edit#heading=h.xgttzgekcivp)

## Definition of done (DoD)
* Acceptance criteria are met.
* Work products are uploaded to the Github repository.
* A pull request is created for each related branch.
* The work products in the pull requests are reviewed.
* The corresponding branches are merged and closed.
* The bill of materials section of the planning documents is updated.
* All defined conventions are complied with.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by zenzeii** [comment]
uploaded here: [https://github.com/amosproj/amos2023ss03-qachat/blob/main/Deliverables/sprint-05/build-process-video.mp4](https://github.com/amosproj/amos2023ss03-qachat/blob/main/Deliverables/sprint-05/build-process-video.mp4)

Note: video is in mp4 format because the mkv format makes the size of the video very large that we can't push to github
